runtime: python27
api_version: 1
threadsafe: true

handlers:
#- url: /
#  static_files: index.html
#  upload: index.html

- url: /.*
  script: maybetodo.app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest